#
# [application.properties]
# =======================================
# This software is licensed under the MIT License.
# However, any distribution or modification must retain this copyright notice.
# See LICENSE for full terms.
# =======================================
# author: "Jiu Liu"
# author_contact: "QQ: 3209174373, GitHub: https://github.com/DCSCDF"
# license: "MIT"
# license_exception: "Mandatory attribution retention"
# UpdateTime: 2026/2/18 11:52
#

spring.application.name=Myblog_dev
server.port=8088
spring.datasource.url=jdbc:mysql://localhost:3306/myblog_sql?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false

spring.datasource.username=jiuliu
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# MyBatis-Plus
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.mapper-locations=classpath*:mapper/*.xml
mybatis-plus.global-config.db-config.id-type=auto
# Sa-Token
#  sa-token: concurrent one login
sa-token.is-concurrent=false
sa-token.timeout=2592000
#sa-token.active-timeout=1800
sa-token.is-share=true
sa-token.token-name=token
sa-token.is-read-cookie=false
sa-token.is-read-header=true
#sa-token.is-read-body=false

#  sa-token: Log out
sa-token.is-log=false
#  sa-token: uuid,simple-uuid,random-32,random-64,random-128,tik
sa-token.token-style=random-128
#  schema.sql
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.sql.init.platform=mysql
spring.sql.init.schema-locations=classpath:schema.sql
captcha.prefix=captcha
captcha.expire.default=10000
captcha.expire.WORD_IMAGE_CLICK=20000
captcha.init-default-resource=true
captcha.local-cache-enabled=false
captcha.local-cache-size=20
captcha.local-cache-wait-time=5000
captcha.local-cache-period=2000
captcha.local-cache-ignored-cache-fields=
captcha.font-path[0]=classpath:font/SimHei.ttf
captcha.secondary.enabled=true
captcha.secondary.expire=120000
captcha.secondary.keyPrefix=captcha:secondary



# CORS  (dev,webUse)
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://localhost:4173

# comment
app.comment.max-nest-level=10

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



